### ISSUE TITLE
Update product (Firefox/Thunderbird) logo icons in https://www.mozilla.jp/

### ISSUE THREAD

**Issue by makotokato** [mozilla-japan/mozilla.jp#4]
トップページ (https://www.mozilla.jp/) のThunderbirdのアイコンがたぶん古いロゴです。

**Comment by dynamis** [comment]
Firefox ロゴも新しくなったので差し替えたい。

**Comment by kyoshino** [comment]
新しいサイトは新しいロゴを入れました。 https://www.mozilla.jp/
