### ISSUE TITLE
No More PHP

### ISSUE THREAD

**Issue by dynamis** [mozilla-japan/mozilla.jp#7]
PHP 使ってることでサーバの維持メンテコストが掛かるが現状動的なコンテンツはトップページのイベント情報を Doorkeeper から取得する箇所や、簡易テンプレートエンジンとしてヘッダフッタを付与しているなど程度だけ。

そろそろ Statis Site Generator に移行して apache/nginx さえあれば大丈夫とか netlify などの静的ホスティングサーバを活用出来るサイトにしたい (ホントは弊社メンテ時代に解決しておくべきだった問題が今頃なんですけど...)。

Hugo (使い慣れてる人がいる)、Next.js (アプリ向けには今は一番)、Gatsby (高速なサイトのテンプレとしてはトップになったかな＆徐々にこなれてきた)、11ty (最近出てきたばかりだけど注目度高い) あたり良いのではなんて話をしていた。

ref: https://www.staticgen.com/

Jekyll は Github pages にしたいわけじゃないので特にメリット無しかな。Vue 系だと vuepress や nuxt だけど他で使ってみても特に愛は芽生えなかったし React 系の方が一般的だろうという想定で。

**Comment by kyoshino** [comment]
先ほど Hugo + Netlify の新しい静的サイトに切り替わりました。レポジトリは https://github.com/mozilla-japan/www.mozilla.jp に作り直したので、ここはアーカイブしましょう。
